### ISSUE TITLE
By Mistake Country India came during Copy Pasting code from previous Code

### ISSUE THREAD

**Issue by pushpendrahpx** [Pushpendrahpx/Data-Structure-Implementation#3]
https://github.com/Pushpendrahpx/Data-Structure-Implementation/blob/770a76660b93c7b95492af671d92938eaa6f2ecd/q1/c.c#L25

**Comment by constantinosgeorgiou** [comment]
I can help with this issue. Would you like me to remove the "India" initialization of the struct?

**Comment by constantinosgeorgiou** [comment]
Fix provided in PR #4
